# docs/openapi.yaml
openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: API for managing contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Contacts
    description: Operations related to contacts
servers:
  - url: http://localhost:3000
    description: Local server
  - url: https://nodejs-hw-mongodb-7-r46q.onrender.com
    description: Deployed server
paths:
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
